var resData={
    "error_code": 200,
    "result": [
        {
            "actualBreakAmount": 1,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 2,
            "exceptionCount": 3,
            "expenditureFreight": 4,
            "frozenFreight": 2,
            "goodsVolume": 1,
            "goodsWeight": 4,
            "orderTime": "2017-04-26",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 5,
            "completeCount": 6,
            "confirmTransportCount": 7,
            "exceptionCount": 8,
            "expenditureFreight": 9,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-25",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 1,
            "breakAmount": 0,
            "cmbAmount": 2,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 3,
            "expenditureFreight": 4,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-24",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-23",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-22",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-21",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },{
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        },
        {
            "actualBreakAmount": 0,
            "breakAmount": 0,
            "cmbAmount": 0,
            "completeCount": 0,
            "confirmTransportCount": 0,
            "exceptionCount": 0,
            "expenditureFreight": 0,
            "frozenFreight": 0,
            "goodsVolume": 0,
            "goodsWeight": 0,
            "orderTime": "2017-04-20",
            "releaseCount": 0,
            "returnAmount": 0
        }
    ]
};